services:
  postgres:
    container_name: postgres_go
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgres # куда складываются данные внутри контейнера
    volumes:
      - ./postgres-data:/data/postgres # postgres-data папка прямо в этом репозитории будет лежать 
    ports:
      - "5432:5432"